server:
  port: 9002

spring:
  redis:
    database: 4
    host: 192.168.100.101
    port: 6379
    password:

  datasource:
    url: jdbc:p6spy:mysql://192.168.100.101:3307/longcom_ums?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: lkwlw@2022
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

  devtools:
    restart:
      enabled: false

#生产环境关闭SQL日志输出
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
